# The starting class for all players for this group.
# "none" will result in no starting class
default: 'none'

# The permission required to profess as any class in this group.
# "none" will result in no permissions being required
permission: 'none'

# Decides what to reset when a player professes into a new class
profess-reset:
  level: 'false'
  attributes: 'false'
  skills: 'false'

# Whether or not this class is reset when players use the reset command
can-reset: 'true'

# Whether or not players professed as the same base class in this group
# are considered allies and cannot attack each other
friendly: 'false'

# Whether or not to show a scoreboard for classes within this group.
# Scoreboards must be enabled for this to work.
show-scoreboard: 'true'

# Percentage of experience lost upon dying.
# This will not cause players to lose levels.
exp-lost-on-death: 0.0

# Number of skill points players start with
starting-skill-points: 1

# How many skill points a player gains every level.
# You can use decimal values for one point every few levels.
# 0.2, for instance, would give one point every 5 levels.
# If use-custom-points is enabled, this is ignored
skill-points-per-level: 1.0

# Number of attribute points players start with
starting-attribute-points: 0

# How many attribute points a player gains every level.
# You can use decimal values for one point every few levels.
# 0.2, for instance, would give one point every 5 levels.
# If use-custom-attribute-points is enabled, this is ignored.
attribute-points-per-level: 1.0

# Whether or not to use custom skill point distribution.
# When enabled, skill points are given based on custom-points
# instead of points-per-level
use-custom-skill-points: 'false'

# Whether or not to use custom attribute point distribution.
# When enabled, attribute points are given based on custom-attribute-points
# instead of attribs-per-level
use-custom-attribute-points: 'false'

# Defines how many skill points players get at specific levels.
# This only applies when use-custom-points is set to "true".
# Numbers on the left are the level the skill points are given.
# Numbers on the right are how many skill points are given.
custom-skill-points:
  5: 1
  10: 1
  15: 1
  20: 1

# Defines how many attribute points players get at specific levels.
# This only applies when use-custom-attribute-points is set to "true".
# Numbers on the left are the level the attribute points are given.
# Numbers on the right are how many attribute points are given.
custom-attribute-points:
  5: 1
  10: 1
  15: 1
  20: 1